#!/bin/bash

# Expect a parameter with the name of the parent folder to stow
[ -z "$1" ] && echo "Parent folder required." && exit 1

# Current path of execution of the script
declare root="$(dirname "$0")/$1/"
[ ! -d "$root" ] && echo "Parent folder not exist." && exit 1

# Target location to unstow from the configuration files
declare home=""
if [[ "$1" == "home" ]]; then
  home=~/
else
  home=/etc/
fi

clean_symlink() {
  local folder=${1:-NULL}
  [ -z $folder ] && echo "Invalid folder path." && return
  local foldername=$(basename $folder)

  echo "Deleting symlink for ${foldername}.."
  stow --target=$home --dir=$root -D $foldername 
  [ $? -ne 0 ] && echo "Failed." && return
}


# Delete a bunch of symlinks
echo "Target location: ${home}"

for folder in $(ls -d -- $root/*/)
do
  clean_symlink $folder
done

