#!/bin/bash

# Input expected: Parent folder from where to stow files
#                 Each folder is tied to a specific target location
[ -z "$1" ] && echo "Parent folder required." && exit 1
[ -z "$2" ] && echo "Target folder not specified. Using default path"

# Using default target to stow files (if not specified otherwise)
declare target=${2:-"~/"}
# Current path of execution of the script
declare root="$(dirname "$0")/$1/"
[ ! -d "$root" ] && echo "Parent folder does not exist." && exit 1

# Stow a file in the target directory
create_symlink() {
  local folder=${1:-NULL}
  [ -z $folder ] && echo "Invalid folder path." && return
  local foldername=$(basename $folder)

  echo "Creating symlink for ${foldername}.."
  # delete if a symlink already exist
  stow --target=$target --dir=$root -D $foldername 
  # create symlink for nvim config
  stow --target=$target --dir=$root $foldername
  [ $? -ne 0 ] && echo "Failed." && return
}


# Create a bunch of symlinks
echo "Target location: ${target}"

for folder in $(ls -d -- $root/*/)
do
  create_symlink $folder
done

