#!/bin/bash

# WARNING: need stow to work
# Check stow is installed
which stow > /dev/null 2>&1
[ $? -ne 0 ] && echo "[ WARNING ] - You need to install stow first.." && exit 1

# Input expected: Parent folder from where to stow files
#                 Each folder is tied to a specific target location
[ -z "$1" ] && echo "Parent folder required." && exit 1
[ -z "$2" ] && echo "Target folder not specified. Using default path"

# Using default target to stow files (if not specified otherwise)
declare target=${2:-$HOME}
# Current path of execution of the script
declare root="$(dirname "$0")/$1"
[ ! -d "$root" ] && echo "Parent folder does not exist." && exit 1

# Stow a file in the target directory
delete_symlink() {
  local folder=${1:-NULL}
  [ -z $folder ] && echo "Invalid folder path." && return 1
  local foldername=$(basename $folder)

  echo "Removing symlink for ${foldername}.."
  # delete if a symlink already exist
  stow --target=$target --dir=$root -D $foldername
  [ $? -ne 0 ] && echo "Failed." && return 1
  return 0
}


# Delete all the symlinks
echo "Target location: ${target}"

for folder in $(ls -d -- $root/*)
do
  delete_symlink $folder
done

